// <auto-generated />
namespace Formula1_new.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class DriverImage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DriverImage));
        
        string IMigrationMetadata.Id
        {
            get { return "202406202258502_DriverImage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
